### ISSUE TITLE
User Story: Deploy Website

### ISSUE THREAD

**Issue by dmuresanu** [dmuresanu/blaze#1]
As a **developer** I can **deploy the website early** so that **I can avoid any technical issues or stress closer to the project submission.**

### Acceptance Criteria

AC1 - The project must be deployed to Heroku
AC2 - The project must use a 3rd party to host images like Cloudinary
AC3 - The code must be stored in GitHub for the assessor to grade

### Tasks

- [ ] Create workspace with Gitpod
- [ ] Connect Github to Heroku
- [ ] Set up environment variables
- [ ] Connect Cloudinary
- [ ] Ensure app is showing deployed on Heroku
