### ISSUE TITLE
User Story: Create User Profile (CRUD)

### ISSUE THREAD

**Issue by dmuresanu** [dmuresanu/blaze#2]
As a **Customer** I can **register a user profile** so that **I can make a booking**

### Acceptance Criteria

AC1 - User must provide all relevant basic information (Name, Phone, Email) to create an account and be able to make a booking.

AC2 - User should be able to login and logout once their account is created.

AC3 - User should have the ability to access a profile page that displays their account overview.

AC4 - User should have the ability to delete their account from the profile page.

### Tasks

- [ ] Create backend profile logic (create backend)
- [ ] Add style and navigation to front end (create functionality with HTML and CSS)
- [ ] Add icons if necessary for ease of use (style to suit web theme)
