### ISSUE TITLE
User Story: Remove Profile (CRUD)

### ISSUE THREAD

**Issue by dmuresanu** [dmuresanu/blaze#4]
As a **Customer** I can **remove my account** so that **I can maintain control over my data and privacy**

### Acceptance Criteria

AC1 - User must be able to select an option to remove their account.

AC2 - Safeguards must be in place to prevent accidental account removal (e.g., Confirmation dialog).

### Tasks

- [ ] Implement account removal logic in the backend.
- [ ] Add an account removal link for signed-in users on the profile page.
- [ ] Style the account removal button with a distinct warning red color to prevent unintended clicks.
- [ ] Add a confirmation dialog to verify the user's intention to delete their account.
