### ISSUE TITLE
User Story: Base Template

### ISSUE THREAD

**Issue by dmuresanu** [dmuresanu/blaze#7]
As a **Developer** I can ** preview the website while coding it** so that **I can make adjustments and verify that the functionality works as intended.**

### Acceptance Criteria

AC1 - The project must include a foundational template.

AC2 - The base template must have all the required links, metadata, and CDNs needed for the project.

AC3 - Must include the links and navigation following Django URL rules.

### Tasks

- [ ] Create `base.html` and add boilerplate code.
- [ ] Add links to static files like CSS and JS.
- [ ] Add CDN links in the head section.
