### ISSUE TITLE
User Story: Book a Reservation

### ISSUE THREAD

**Issue by dmuresanu** [dmuresanu/blaze#8]
As a **Customer** I can **place a booking** so that **I can dine at the venue.**

### Acceptance Criteria

AC1 - The user must have an account to make a booking.

AC2 - The user must have all the required information on their profile (name, email, phone number).

AC3 - The admin must be able to view the reservation on the backend for approval.

AC4 - The user must be able to see the reservation status from their profile.

### Tasks

- [ ] Create booking model (backend).
- [ ] Create booking form (functionality with HTML and CSS).
- [ ] Add booking details to the user's profile.
- [ ] Add notification for the user once the booking is accepted.
- [ ] Add notification if the booking is not accepted.
