### ISSUE TITLE
User Story: Events

### ISSUE THREAD

**Issue by dmuresanu** [dmuresanu/blaze#9]
As a **Business Owner** I can **promote upcoming events** so that **users can can make reservations.**

### Acceptance Criteria

AC1 - Users must have an account.

AC2 - Events should be displayed on a blog-style page with an image and description.

AC3 - If the event is more than 30 days away, ticket reservations will be unavailable, and instead, a countdown timer will be shown.

AC4 - If the event has sold out, it will be marked as unavailable for booking.

AC5 - The admin must be able to view a list of attendees for the event.

AC6 - The user must be able to view the event in their booking history on their profile.

AC7 - The user should be able to cancel their ticket if they cannot attend, returning it to the event portal.

### Tasks

- [ ] Create event models, URLs, and logic (backend development).
- [ ] Develop event links and pages (frontend functionality with HTML and CSS).
- [ ] Add confirmed bookings to user profiles.
- [ ] Allow users to cancel tickets.
